# Eksempel på bruk av POST og GET i PxWebApi versjon 2 i Python

## Det nye APIet tilbyr både http POST som før, og http GET som er nytt

#### benytter biblioteket pyjstat for JSON-stat

In [1]:
import pandas as pd
import requests
from pyjstat import pyjstat

## Post spørring og få Pandas dataframe i retur
Nytt: Språk og utformat angis i URL

In [2]:
# Eksport av laks
POST_URL = 'https://data.ssb.no/api/pxwebapi/v2/tables/03024/data?lang=no&outputFormat=json-stat2'

API spørring, Det er en annen struktur enn i PxWebApi Versjon 1  - henter fryst og fersk laks fra og med uke 1 2025. `from()` er nytt i v2.

In [3]:
payload = {"selection": [
			{"variableCode": "VareGrupper2", 
             "valueCodes": [
                 "01", "02"
             ] 
            },
			{"variableCode": "ContentsCode", 
             "valueCodes": [
                 "Vekt", "Kilopris"
             ] 
            },
			{"variableCode": "Tid", 
             "valueCodes": ["from(2025U01)"] }  
		]
		}

In [4]:
resultat = requests.post(POST_URL, json = payload)

In [5]:
print(resultat)

<Response [200]>

Resultat gir bare http statuskode - 200 hvis OK. Body ligger i resultat.text

In [6]:
dataset = pyjstat.Dataset.read(resultat.text)

In [7]:
df = dataset.write('dataframe')

In [8]:
df.head()

           varegruppe statistikkvariabel      uke    value
0  Fersk oppalen laks        Vekt (tonn)  2025U01  11364.0
1  Fersk oppalen laks        Vekt (tonn)  2025U02  15939.0
2  Fersk oppalen laks        Vekt (tonn)  2025U03  17325.0
3  Fersk oppalen laks        Vekt (tonn)  2025U04  15564.0
4  Fersk oppalen laks        Vekt (tonn)  2025U05  16370.0

In [9]:
df.tail()

              varegruppe statistikkvariabel      uke  value
347  Frosen oppalen laks      Kilopris (kr)  2026U32  74.09
348  Frosen oppalen laks      Kilopris (kr)  2026U33  69.12
349  Frosen oppalen laks      Kilopris (kr)  2026U34  75.03
350  Frosen oppalen laks      Kilopris (kr)  2026U35  72.94
351  Frosen oppalen laks      Kilopris (kr)  2026U36  68.07

In [10]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 352 entries, 0 to 351
Data columns (total 4 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   varegruppe          352 non-null    str
 1   statistikkvariabel  352 non-null    str
 2   uke                 352 non-null    str
 3   value               352 non-null    float64
dtypes: float64(1), str(3)
memory usage: 24.0 KB

In [11]:
print(resultat.text)

{"version":"2.0","class":"dataset","label":"03024: Eksport av oppalen laks, etter varegruppe og uke","source":"Statistisk sentralbyrå","updated":"2026-09-09T06:00:00Z","role":{"time":["Tid"],"metric":["ContentsCode"]},"id":["VareGrupper2","ContentsCode","Tid"],"size":[2,2,88],"dimension":{"VareGrupper2":{"label":"varegruppe","category":{"index":{"01":0,"02":1},"label":{"01":"Fersk oppalen laks","02":"Frosen oppalen laks"}},"extension":{"elimination":false,"show":"value"}},"ContentsCode":{"label":"statistikkvariabel","category":{"index":{"Vekt":0,"Kilopris":1},"label":{"Vekt":"Vekt (tonn)","Kilopris":"Kilopris (kr)"},"unit":{"Vekt":{"base":"tonn","decimals":0},"Kilopris":{"base":"kr","decimals":2}}},"extension":{"elimination":false,"refperiod":{"Vekt":"Utgangen av veka","Kilopris":"Utgangen av veka"},"show":"value","measuringType":{"Vekt":"Flow","Kilopris":"Flow"},"priceType":{"Vekt":"NotApplicable","Kilopris":"NotApplicable"},"adjustment":{"Vekt":"None","Kilopris":"None"},"alternativeText":{"Vekt":"Vekt (tonn)","Kilopris":"Kilopris (kr)"}},"link":{"describedby":[{"extension":{"Vekt":"urn:ssb:conceptvariable:vardok:2982"}}]}},"Tid":{"label":"uke","category":{"index":{"2025U01":0,"2025U02":1,"2025U03":2,"2025U04":3,"2025U05":4,"2025U06":5,"2025U07":6,"2025U08":7,"2025U09":8,"2025U10":9,"2025U11":10,"2025U12":11,"2025U13":12,"2025U14":13,"2025U15":14,"2025U16":15,"2025U17":16,"2025U18":17,"2025U19":18,"2025U20":19,"2025U21":20,"2025U22":21,"2025U23":22,"2025U24":23,"2025U25":24,"2025U26":25,"2025U27":26,"2025U28":27,"2025U29":28,"2025U30":29,"2025U31":30,"2025U32":31,"2025U33":32,"2025U34":33,"2025U35":34,"2025U36":35,"2025U37":36,"2025U38":37,"2025U39":38,"2025U40":39,"2025U41":40,"2025U42":41,"2025U43":42,"2025U44":43,"2025U45":44,"2025U46":45,"2025U47":46,"2025U48":47,"2025U49":48,"2025U50":49,"2025U51":50,"2025U52":51,"2026U01":52,"2026U02":53,"2026U03":54,"2026U04":55,"2026U05":56,"2026U06":57,"2026U07":58,"2026U08":59,"2026U09":60,"2026U10":61,"2026U11":62,"2026U12":63,"2026U13":64,"2026U14":65,"2026U15":66,"2026U16":67,"2026U17":68,"2026U18":69,"2026U19":70,"2026U20":71,"2026U21":72,"2026U22":73,"2026U23":74,"2026U24":75,"2026U25":76,"2026U26":77,"2026U27":78,"2026U28":79,"2026U29":80,"2026U30":81,"2026U31":82,"2026U32":83,"2026U33":84,"2026U34":85,"2026U35":86,"2026U36":87},"label":{"2025U01":"2025U01","2025U02":"2025U02","2025U03":"2025U03","2025U04":"2025U04","2025U05":"2025U05","2025U06":"2025U06","2025U07":"2025U07","2025U08":"2025U08","2025U09":"2025U09","2025U10":"2025U10","2025U11":"2025U11","2025U12":"2025U12","2025U13":"2025U13","2025U14":"2025U14","2025U15":"2025U15","2025U16":"2025U16","2025U17":"2025U17","2025U18":"2025U18","2025U19":"2025U19","2025U20":"2025U20","2025U21":"2025U21","2025U22":"2025U22","2025U23":"2025U23","2025U24":"2025U24","2025U25":"2025U25","2025U26":"2025U26","2025U27":"2025U27","2025U28":"2025U28","2025U29":"2025U29","2025U30":"2025U30","2025U31":"2025U31","2025U32":"2025U32","2025U33":"2025U33","2025U34":"2025U34","2025U35":"2025U35","2025U36":"2025U36","2025U37":"2025U37","2025U38":"2025U38","2025U39":"2025U39","2025U40":"2025U40","2025U41":"2025U41","2025U42":"2025U42","2025U43":"2025U43","2025U44":"2025U44","2025U45":"2025U45","2025U46":"2025U46","2025U47":"2025U47","2025U48":"2025U48","2025U49":"2025U49","2025U50":"2025U50","2025U51":"2025U51","2025U52":"2025U52","2026U01":"2026U01","2026U02":"2026U02","2026U03":"2026U03","2026U04":"2026U04","2026U05":"2026U05","2026U06":"2026U06","2026U07":"2026U07","2026U08":"2026U08","2026U09":"2026U09","2026U10":"2026U10","2026U11":"2026U11","2026U12":"2026U12","2026U13":"2026U13","2026U14":"2026U14","2026U15":"2026U15","2026U16":"2026U16","2026U17":"2026U17","2026U18":"2026U18","2026U19":"2026U19","2026U20":"2026U20","2026U21":"2026U21","2026U22":"2026U22","2026U23":"2026U23","2026U24":"2026U24","2026U25":"2026U25","2026U26":"2026U26","2026U27":"2026U27","2026U28":"2026U28","2026U29":"2026U29","2026U30":"2026U30","2026U31":"2026U31","2026U32":"2026U32","2026U33":"2026U33","2026U34":"2026U34","2026U35":"2026U35","2026U36":"2026U36"}},"extension":{"elimination":false,"show":"code"}}},"extension":{"px":{"infofile":"None","tableid":"03024","decimals":0,"official-statistics":true,"aggregallowed":false,"copyright":false,"language":"no","contents":"03024: Eksport av oppalen laks,","descriptiondefault":false,"heading":["ContentsCode","Tid"],"stub":["VareGrupper2"],"matrix":"03024","subject-code":"ut","subject-area":"Utenriksøkonomi"},"discontinued":null,"contact":[{"name":"Utenrikshandel","organization":"Statistisk sentralbyrå","phone":"62 88 50 00","mail":"utenrikshandel@ssb.no","raw":" Utenrikshandel, Statistisk sentralbyrå# +47 62 88 50 00#utenrikshandel@ssb.no"}]},"value":[11364,15939,17325,15564,16370,15184,15966,15536,18067,17116,17467,18172,18828,19053,20009,13620,18343,18958,18073,19523,20466,18223,19164,18505,22332,21712,22602,24500,24412,26055,25317,25796,27320,28180,27726,26744,24791,24495,23396,24009,26112,26448,25886,24875,24111,23488,24038,24188,23754,25596,23942,12527,13496,21000,22239,20924,20538,19798,19990,17853,17853,16113,17120,18308,21292,16503,18610,20224,19294,17714,21966,20806,22386,19539,22409,22593,25866,26564,26491,26117,28165,25822,26958,28602,28762,31378,30487,30798,125.36,117.77,105.08,98.43,94.49,92.18,93.23,92.97,92.67,87,88.64,89.09,84.45,76.4,78.56,95.33,89.19,75.35,74.31,77.06,75.89,70.42,72.42,82.73,76.33,68.74,70.28,67.29,68.13,65.1,60.58,62.05,64.38,65.13,65.86,70.2,74.99,77.4,79.91,77.68,75.38,73.74,78.25,80.55,78.08,80.1,84.54,82.5,88.83,95.84,88.71,103.59,100.4,92.33,83.65,83.09,81.29,92.86,93.6,84.89,81.34,88.03,94.98,94.4,90.55,89.13,85.17,77.31,76.49,83.51,82.58,77.29,73.94,76.29,72.78,69.85,70.31,68.14,67.31,69.54,69.64,71.31,73.57,74.9,72.66,73.52,71.87,69.71,255,393,645,738,510,706,740,544,520,538,368,473,560,612,666,162,534,479,530,498,703,686,721,651,688,440,628,657,606,718,854,624,732,747,597,921,708,864,796,701,606,568,740,666,569,748,454,629,506,338,325,195,61,348,355,468,749,599,468,409,357,531,572,931,736,208,421,561,486,324,571,363,516,423,250,587,549,609,272,503,838,736,697,638,751,727,720,546,84.19,90.27,84.59,88.27,96.78,92.27,86.96,82.23,79.5,93.43,76.23,95.18,83.03,76.26,76.87,84.84,82.26,84.86,77.32,89.4,82.63,70.85,76.8,75.44,73.33,72.93,76.87,77.98,76.83,70.76,71.67,65.93,75.74,70.19,65.09,70.89,64.45,73.8,71.33,69.75,72,72.47,74.86,78.2,78.16,72.24,76.24,77.24,83.17,75.79,75.38,75.87,73.92,77.86,66.06,73.14,71.44,75.07,68.58,67.18,70.82,70.92,74.43,72.52,73.91,63.72,75.37,71.61,69.21,80.78,68.27,70.77,65.27,69.98,74.77,74.61,74.01,68.02,74.44,72.32,72.37,72.08,72.79,74.09,69.12,75.03,72.94,68.07]}

## Henter noen overordnete metadata fra JSON-stat datasettet

In [12]:
tittel = dataset['label']
print(tittel)

03024: Eksport av oppalen laks, etter varegruppe og uke

In [13]:
last_update = dataset['updated']
print(last_update)

2026-09-09T06:00:00Z

In [14]:
source = dataset['source']
print(source)

Statistisk sentralbyrå

'Role' gir snarveier til statistikkvariabel(metric), Tid og evt. Geo

In [15]:
ds_roles = dataset['role']
print(ds_roles)

OrderedDict({'time': ['Tid'], 'metric': ['ContentsCode']})

Her er noen nye metadata

In [16]:
ds_id = dataset['extension']['px']['tableid']
print(ds_id)

03024

In [17]:
ds_shorttit = dataset['extension']['px']['contents']
print(ds_shorttit)

03024: Eksport av oppalen laks,

Sjekk om tabellen har fotnote

In [18]:
if 'note' in dataset:
    ds_note = dataset['note']
    print(ds_note)

In [19]:
ds_dims = dataset['id']
ds_dims

['VareGrupper2', 'ContentsCode', 'Tid']

In [20]:
ds_dim = dataset['dimension']['VareGrupper2']['label']
ds_dim

'varegruppe'

In [21]:
ds_shorttit,' etter ',ds_dim

('03024: Eksport av oppalen laks,', ' etter ', 'varegruppe')

In [22]:
ds_dimcat = dataset['dimension']['ContentsCode']
ds_dimcat

OrderedDict([('label', 'statistikkvariabel'),
             ('category',
              OrderedDict([('index',
                            OrderedDict([('Vekt', 0), ('Kilopris', 1)])),
                           ('label',
                            OrderedDict([('Vekt', 'Vekt (tonn)'),
                                         ('Kilopris', 'Kilopris (kr)')])),
                           ('unit',
                            OrderedDict([('Vekt',
                                          OrderedDict([('base', 'tonn'),
                                                       ('decimals', 0)])),
                                         ('Kilopris',
                                          OrderedDict([('base', 'kr'),
                                                       ('decimals',
                                                        2)]))]))])),
             ('extension',
              OrderedDict([('elimination', False),
                           ('refperiod',
                            OrderedDict([('Vekt', 'Utgangen av veka'),
                                         ('Kilopris', 'Utgangen av veka')])),
                           ('show', 'value'),
                           ('measuringType',
                            OrderedDict([('Vekt', 'Flow'),
                                         ('Kilopris', 'Flow')])),
                           ('priceType',
                            OrderedDict([('Vekt', 'NotApplicable'),
                                         ('Kilopris', 'NotApplicable')])),
                           ('adjustment',
                            OrderedDict([('Vekt', 'None'),
                                         ('Kilopris', 'None')])),
                           ('alternativeText',
                            OrderedDict([('Vekt', 'Vekt (tonn)'),
                                         ('Kilopris', 'Kilopris (kr)')]))])),
             ('link',
              OrderedDict([('describedby',
                            [OrderedDict([('extension',
                                           OrderedDict([('Vekt',
                                                         'urn:ssb:conceptvariable:vardok:2982')]))])])]))])

In [23]:
ds_var = dataset['dimension']['VareGrupper2']['category']['label']['01']
ds_var

'Fersk oppalen laks'

## GET - PxWebApi2

Ferdigdefinerte datasett er nytt versjon 2 av PxWebApi. 

Vi bruker POST-URLen over med http GET til å gi oss et ferdigdefinert datasett.

Vi kunne tatt vekk parametrene ?lang=no&outputFormat=json-stat2 fordi disse er satt i /config

In [24]:
print(requests.get(POST_URL).url)

https://data.ssb.no/api/pxwebapi/v2/tables/03024/data?lang=no&outputFormat=json-stat2

In [25]:
resultat_get = requests.get(POST_URL)

In [26]:
res_get = resultat_get.text

In [27]:
dataset_get = pyjstat.Dataset.read(res_get)

In [28]:
# dataset_get

In [29]:
df_get = dataset_get.write('dataframe')

In [30]:
df_get

            varegruppe      uke statistikkvariabel     value
0   Fersk oppalen laks  2026U36        Vekt (tonn)  30798.00
1   Fersk oppalen laks  2026U36      Kilopris (kr)     69.71
2  Frosen oppalen laks  2026U36        Vekt (tonn)    546.00
3  Frosen oppalen laks  2026U36      Kilopris (kr)     68.07

Vi kan også bruke get-url med parametre: fersk laks, vekt, pris i 2025

`&valueCodes[VareGrupper2]=01&valueCodes[ContentsCode]=Vekt,Kilopris&valueCodes[Tid]=2025*`

In [31]:
GET_URL = 'https://data.ssb.no/api/pxwebapi/v2/tables/03024/data?lang=no&valueCodes[VareGrupper2]=01&valueCodes[ContentsCode]=Vekt,Kilopris&valueCodes[Tid]=from(2025U01)'

In [32]:
resultat_get1 = requests.get(GET_URL)

In [33]:
dataset1_get = pyjstat.Dataset.read(resultat_get1.text)

In [34]:
df1 = dataset1_get.write('dataframe')

In [35]:
df1.tail(2)

             varegruppe statistikkvariabel      uke  value
174  Fersk oppalen laks      Kilopris (kr)  2026U35  71.87
175  Fersk oppalen laks      Kilopris (kr)  2026U36  69.71

### Nytt i PxWebApi v2. Parametre for styring av CSV-output.
Dette er samme som POST spørringen, men med utformat CSV. 

For utformatene csv, html og xlsx kan du i `outputformatparams` spesifisere visning av kode/tekst og tabelltittel:

- `UseCodes` (vis koder) 
- `UseTexts` (vis tekst) 
- `UseCodesAndTexts` (vis koder og tekst) 
- `IncludeTitle` (ta med tabelltittel) 

Du kan også bruke `stub` for å angi hvilke variabler du vil plassere i forspalten av tabellen og evt. `heading` for de variablene du vil plassere i tabellhodet Plasserer du alle variabler i stub, får du en såkalt pivotvennlig tabell.

Og for csv-filer kan du velge mellom ulike skilletegn: 

- `SeparatorTab` (tabulator mellom kolonner) 
- `SparatorSpace` (mellomrom mellom kolonner) 
- `SeparatorSemicolon` (semikolon mellom kolonner) 


Output i eksempelet her er semikolonseparert, med både kode og tekst. Statistikkvariabel i hode, rekkefølge på kolonner er Varegruppe2 og Tid

`outputformat = csv`

`outputformatparams = separatorsemicolon, usecodesandtexts`

`heading = ContentsCode`

`stub = VareGrupper2, Tid`

In [36]:
CSV_URL = 'https://data.ssb.no/api/pxwebapi/v2/tables/03024/data?lang=no\
&outputformat=csv\
&outputformatparams=separatorsemicolon,usecodesandtexts\
&heading=ContentsCode&stub=VareGrupper2,Tid\
&valuecodes[ContentsCode]=Vekt,Kilopris\
&valuecodes[Varegrupper2]=01,02\
&valuecodes[Tid]=from(2025U01)'

Merk: Har lagt til `\`for å øke lesbarheten.

Det er mulig å angi URL med CSV direkte til Pandas, med pd.read_csv(), og få en dataframe.

In [37]:
df = pd.read_csv(CSV_URL, delimiter = ';')

In [38]:
df.head(8)

,VareGrupper2 - varegruppe,Tid - uke,Vekt - Vekt (tonn),Kilopris - Kilopris (kr)
0,01 - Fersk oppalen laks,2025U01 - 2025U01,11364,125.36
1,01 - Fersk oppalen laks,2025U02 - 2025U02,15939,117.77
2,01 - Fersk oppalen laks,2025U03 - 2025U03,17325,105.08
3,01 - Fersk oppalen laks,2025U04 - 2025U04,15564,98.43
4,01 - Fersk oppalen laks,2025U05 - 2025U05,16370,94.49
5,01 - Fersk oppalen laks,2025U06 - 2025U06,15184,92.18
6,01 - Fersk oppalen laks,2025U07 - 2025U07,15966,93.23
7,01 - Fersk oppalen laks,2025U08 - 2025U08,15536,92.97

Det samme med `requests`. Det blir mer omstendelig om en ikke bruker URL direkte

In [39]:
resultat_csv = requests.get(CSV_URL)

In [40]:
resultat_csv

In [41]:
r_csv = resultat_csv.text

In [42]:
r_csv

'"VareGrupper2 - varegruppe";"Tid - uke";"Vekt - Vekt (tonn)";"Kilopris - Kilopris (kr)"\r\n"01 - Fersk oppalen laks";"2025U01 - 2025U01";11364;125.36\r\n"01 - Fersk oppalen laks";"2025U02 - 2025U02";15939;117.77\r\n"01 - Fersk oppalen laks";"2025U03 - 2025U03";17325;105.08\r\n"01 - Fersk oppalen laks";"2025U04 - 2025U04";15564;98.43\r\n"01 - Fersk oppalen laks";"2025U05 - 2025U05";16370;94.49\r\n"01 - Fersk oppalen laks";"2025U06 - 2025U06";15184;92.18\r\n"01 - Fersk oppalen laks";"2025U07 - 2025U07";15966;93.23\r\n"01 - Fersk oppalen laks";"2025U08 - 2025U08";15536;92.97\r\n"01 - Fersk oppalen laks";"2025U09 - 2025U09";18067;92.67\r\n"01 - Fersk oppalen laks";"2025U10 - 2025U10";17116;87.00\r\n"01 - Fersk oppalen laks";"2025U11 - 2025U11";17467;88.64\r\n"01 - Fersk oppalen laks";"2025U12 - 2025U12";18172;89.09\r\n"01 - Fersk oppalen laks";"2025U13 - 2025U13";18828;84.45\r\n"01 - Fersk oppalen laks";"2025U14 - 2025U14";19053;76.40\r\n"01 - Fersk oppalen laks";"2025U15 - 2025U15";20009;78.56\r\n"01 - Fersk oppalen laks";"2025U16 - 2025U16";13620;95.33\r\n"01 - Fersk oppalen laks";"2025U17 - 2025U17";18343;89.19\r\n"01 - Fersk oppalen laks";"2025U18 - 2025U18";18958;75.35\r\n"01 - Fersk oppalen laks";"2025U19 - 2025U19";18073;74.31\r\n"01 - Fersk oppalen laks";"2025U20 - 2025U20";19523;77.06\r\n"01 - Fersk oppalen laks";"2025U21 - 2025U21";20466;75.89\r\n"01 - Fersk oppalen laks";"2025U22 - 2025U22";18223;70.42\r\n"01 - Fersk oppalen laks";"2025U23 - 2025U23";19164;72.42\r\n"01 - Fersk oppalen laks";"2025U24 - 2025U24";18505;82.73\r\n"01 - Fersk oppalen laks";"2025U25 - 2025U25";22332;76.33\r\n"01 - Fersk oppalen laks";"2025U26 - 2025U26";21712;68.74\r\n"01 - Fersk oppalen laks";"2025U27 - 2025U27";22602;70.28\r\n"01 - Fersk oppalen laks";"2025U28 - 2025U28";24500;67.29\r\n"01 - Fersk oppalen laks";"2025U29 - 2025U29";24412;68.13\r\n"01 - Fersk oppalen laks";"2025U30 - 2025U30";26055;65.10\r\n"01 - Fersk oppalen laks";"2025U31 - 2025U31";25317;60.58\r\n"01 - Fersk oppalen laks";"2025U32 - 2025U32";25796;62.05\r\n"01 - Fersk oppalen laks";"2025U33 - 2025U33";27320;64.38\r\n"01 - Fersk oppalen laks";"2025U34 - 2025U34";28180;65.13\r\n"01 - Fersk oppalen laks";"2025U35 - 2025U35";27726;65.86\r\n"01 - Fersk oppalen laks";"2025U36 - 2025U36";26744;70.20\r\n"01 - Fersk oppalen laks";"2025U37 - 2025U37";24791;74.99\r\n"01 - Fersk oppalen laks";"2025U38 - 2025U38";24495;77.40\r\n"01 - Fersk oppalen laks";"2025U39 - 2025U39";23396;79.91\r\n"01 - Fersk oppalen laks";"2025U40 - 2025U40";24009;77.68\r\n"01 - Fersk oppalen laks";"2025U41 - 2025U41";26112;75.38\r\n"01 - Fersk oppalen laks";"2025U42 - 2025U42";26448;73.74\r\n"01 - Fersk oppalen laks";"2025U43 - 2025U43";25886;78.25\r\n"01 - Fersk oppalen laks";"2025U44 - 2025U44";24875;80.55\r\n"01 - Fersk oppalen laks";"2025U45 - 2025U45";24111;78.08\r\n"01 - Fersk oppalen laks";"2025U46 - 2025U46";23488;80.10\r\n"01 - Fersk oppalen laks";"2025U47 - 2025U47";24038;84.54\r\n"01 - Fersk oppalen laks";"2025U48 - 2025U48";24188;82.50\r\n"01 - Fersk oppalen laks";"2025U49 - 2025U49";23754;88.83\r\n"01 - Fersk oppalen laks";"2025U50 - 2025U50";25596;95.84\r\n"01 - Fersk oppalen laks";"2025U51 - 2025U51";23942;88.71\r\n"01 - Fersk oppalen laks";"2025U52 - 2025U52";12527;103.59\r\n"01 - Fersk oppalen laks";"2026U01 - 2026U01";13496;100.40\r\n"01 - Fersk oppalen laks";"2026U02 - 2026U02";21000;92.33\r\n"01 - Fersk oppalen laks";"2026U03 - 2026U03";22239;83.65\r\n"01 - Fersk oppalen laks";"2026U04 - 2026U04";20924;83.09\r\n"01 - Fersk oppalen laks";"2026U05 - 2026U05";20538;81.29\r\n"01 - Fersk oppalen laks";"2026U06 - 2026U06";19798;92.86\r\n"01 - Fersk oppalen laks";"2026U07 - 2026U07";19990;93.60\r\n"01 - Fersk oppalen laks";"2026U08 - 2026U08";17853;84.89\r\n"01 - Fersk oppalen laks";"2026U09 - 2026U09";17853;81.34\r\n"01 - Fersk oppalen laks";"2026U10 - 2026U10";16113;88.03\r\n"01 - Fersk oppalen laks";"2026U11 - 2026U11";17120;94.98\r\n"01 - Fersk oppalen laks";"2026U12 - 2026U12";18308;94.40\r\n"01 - Fersk oppalen laks";"2026U13 - 2026U13";21292;90.55\r\n"01 - Fersk oppalen laks";"2026U14 - 2026U14";16503;89.13\r\n"01 - Fersk oppalen laks";"2026U15 - 2026U15";18610;85.17\r\n"01 - Fersk oppalen laks";"2026U16 - 2026U16";20224;77.31\r\n"01 - Fersk oppalen laks";"2026U17 - 2026U17";19294;76.49\r\n"01 - Fersk oppalen laks";"2026U18 - 2026U18";17714;83.51\r\n"01 - Fersk oppalen laks";"2026U19 - 2026U19";21966;82.58\r\n"01 - Fersk oppalen laks";"2026U20 - 2026U20";20806;77.29\r\n"01 - Fersk oppalen laks";"2026U21 - 2026U21";22386;73.94\r\n"01 - Fersk oppalen laks";"2026U22 - 2026U22";19539;76.29\r\n"01 - Fersk oppalen laks";"2026U23 - 2026U23";22409;72.78\r\n"01 - Fersk oppalen laks";"2026U24 - 2026U24";22593;69.85\r\n"01 - Fersk oppalen laks";"2026U25 - 2026U25";25866;70.31\r\n"01 - Fersk oppalen laks";"2026U26 - 2026U26";26564;68.14\r\n"01 - Fersk oppalen laks";"2026U27 - 2026U27";26491;67.31\r\n"01 - Fersk oppalen laks";"2026U28 - 2026U28";26117;69.54\r\n"01 - Fersk oppalen laks";"2026U29 - 2026U29";28165;69.64\r\n"01 - Fersk oppalen laks";"2026U30 - 2026U30";25822;71.31\r\n"01 - Fersk oppalen laks";"2026U31 - 2026U31";26958;73.57\r\n"01 - Fersk oppalen laks";"2026U32 - 2026U32";28602;74.90\r\n"01 - Fersk oppalen laks";"2026U33 - 2026U33";28762;72.66\r\n"01 - Fersk oppalen laks";"2026U34 - 2026U34";31378;73.52\r\n"01 - Fersk oppalen laks";"2026U35 - 2026U35";30487;71.87\r\n"01 - Fersk oppalen laks";"2026U36 - 2026U36";30798;69.71\r\n"02 - Frosen oppalen laks";"2025U01 - 2025U01";255;84.19\r\n"02 - Frosen oppalen laks";"2025U02 - 2025U02";393;90.27\r\n"02 - Frosen oppalen laks";"2025U03 - 2025U03";645;84.59\r\n"02 - Frosen oppalen laks";"2025U04 - 2025U04";738;88.27\r\n"02 - Frosen oppalen laks";"2025U05 - 2025U05";510;96.78\r\n"02 - Frosen oppalen laks";"2025U06 - 2025U06";706;92.27\r\n"02 - Frosen oppalen laks";"2025U07 - 2025U07";740;86.96\r\n"02 - Frosen oppalen laks";"2025U08 - 2025U08";544;82.23\r\n"02 - Frosen oppalen laks";"2025U09 - 2025U09";520;79.50\r\n"02 - Frosen oppalen laks";"2025U10 - 2025U10";538;93.43\r\n"02 - Frosen oppalen laks";"2025U11 - 2025U11";368;76.23\r\n"02 - Frosen oppalen laks";"2025U12 - 2025U12";473;95.18\r\n"02 - Frosen oppalen laks";"2025U13 - 2025U13";560;83.03\r\n"02 - Frosen oppalen laks";"2025U14 - 2025U14";612;76.26\r\n"02 - Frosen oppalen laks";"2025U15 - 2025U15";666;76.87\r\n"02 - Frosen oppalen laks";"2025U16 - 2025U16";162;84.84\r\n"02 - Frosen oppalen laks";"2025U17 - 2025U17";534;82.26\r\n"02 - Frosen oppalen laks";"2025U18 - 2025U18";479;84.86\r\n"02 - Frosen oppalen laks";"2025U19 - 2025U19";530;77.32\r\n"02 - Frosen oppalen laks";"2025U20 - 2025U20";498;89.40\r\n"02 - Frosen oppalen laks";"2025U21 - 2025U21";703;82.63\r\n"02 - Frosen oppalen laks";"2025U22 - 2025U22";686;70.85\r\n"02 - Frosen oppalen laks";"2025U23 - 2025U23";721;76.80\r\n"02 - Frosen oppalen laks";"2025U24 - 2025U24";651;75.44\r\n"02 - Frosen oppalen laks";"2025U25 - 2025U25";688;73.33\r\n"02 - Frosen oppalen laks";"2025U26 - 2025U26";440;72.93\r\n"02 - Frosen oppalen laks";"2025U27 - 2025U27";628;76.87\r\n"02 - Frosen oppalen laks";"2025U28 - 2025U28";657;77.98\r\n"02 - Frosen oppalen laks";"2025U29 - 2025U29";606;76.83\r\n"02 - Frosen oppalen laks";"2025U30 - 2025U30";718;70.76\r\n"02 - Frosen oppalen laks";"2025U31 - 2025U31";854;71.67\r\n"02 - Frosen oppalen laks";"2025U32 - 2025U32";624;65.93\r\n"02 - Frosen oppalen laks";"2025U33 - 2025U33";732;75.74\r\n"02 - Frosen oppalen laks";"2025U34 - 2025U34";747;70.19\r\n"02 - Frosen oppalen laks";"2025U35 - 2025U35";597;65.09\r\n"02 - Frosen oppalen laks";"2025U36 - 2025U36";921;70.89\r\n"02 - Frosen oppalen laks";"2025U37 - 2025U37";708;64.45\r\n"02 - Frosen oppalen laks";"2025U38 - 2025U38";864;73.80\r\n"02 - Frosen oppalen laks";"2025U39 - 2025U39";796;71.33\r\n"02 - Frosen oppalen laks";"2025U40 - 2025U40";701;69.75\r\n"02 - Frosen oppalen laks";"2025U41 - 2025U41";606;72.00\r\n"02 - Frosen oppalen laks";"2025U42 - 2025U42";568;72.47\r\n"02 - Frosen oppalen laks";"2025U43 - 2025U43";740;74.86\r\n"02 - Frosen oppalen laks";"2025U44 - 2025U44";666;78.20\r\n"02 - Frosen oppalen laks";"2025U45 - 2025U45";569;78.16\r\n"02 - Frosen oppalen laks";"2025U46 - 2025U46";748;72.24\r\n"02 - Frosen oppalen laks";"2025U47 - 2025U47";454;76.24\r\n"02 - Frosen oppalen laks";"2025U48 - 2025U48";629;77.24\r\n"02 - Frosen oppalen laks";"2025U49 - 2025U49";506;83.17\r\n"02 - Frosen oppalen laks";"2025U50 - 2025U50";338;75.79\r\n"02 - Frosen oppalen laks";"2025U51 - 2025U51";325;75.38\r\n"02 - Frosen oppalen laks";"2025U52 - 2025U52";195;75.87\r\n"02 - Frosen oppalen laks";"2026U01 - 2026U01";61;73.92\r\n"02 - Frosen oppalen laks";"2026U02 - 2026U02";348;77.86\r\n"02 - Frosen oppalen laks";"2026U03 - 2026U03";355;66.06\r\n"02 - Frosen oppalen laks";"2026U04 - 2026U04";468;73.14\r\n"02 - Frosen oppalen laks";"2026U05 - 2026U05";749;71.44\r\n"02 - Frosen oppalen laks";"2026U06 - 2026U06";599;75.07\r\n"02 - Frosen oppalen laks";"2026U07 - 2026U07";468;68.58\r\n"02 - Frosen oppalen laks";"2026U08 - 2026U08";409;67.18\r\n"02 - Frosen oppalen laks";"2026U09 - 2026U09";357;70.82\r\n"02 - Frosen oppalen laks";"2026U10 - 2026U10";531;70.92\r\n"02 - Frosen oppalen laks";"2026U11 - 2026U11";572;74.43\r\n"02 - Frosen oppalen laks";"2026U12 - 2026U12";931;72.52\r\n"02 - Frosen oppalen laks";"2026U13 - 2026U13";736;73.91\r\n"02 - Frosen oppalen laks";"2026U14 - 2026U14";208;63.72\r\n"02 - Frosen oppalen laks";"2026U15 - 2026U15";421;75.37\r\n"02 - Frosen oppalen laks";"2026U16 - 2026U16";561;71.61\r\n"02 - Frosen oppalen laks";"2026U17 - 2026U17";486;69.21\r\n"02 - Frosen oppalen laks";"2026U18 - 2026U18";324;80.78\r\n"02 - Frosen oppalen laks";"2026U19 - 2026U19";571;68.27\r\n"02 - Frosen oppalen laks";"2026U20 - 2026U20";363;70.77\r\n"02 - Frosen oppalen laks";"2026U21 - 2026U21";516;65.27\r\n"02 - Frosen oppalen laks";"2026U22 - 2026U22";423;69.98\r\n"02 - Frosen oppalen laks";"2026U23 - 2026U23";250;74.77\r\n"02 - Frosen oppalen laks";"2026U24 - 2026U24";587;74.61\r\n"02 - Frosen oppalen laks";"2026U25 - 2026U25";549;74.01\r\n"02 - Frosen oppalen laks";"2026U26 - 2026U26";609;68.02\r\n"02 - Frosen oppalen laks";"2026U27 - 2026U27";272;74.44\r\n"02 - Frosen oppalen laks";"2026U28 - 2026U28";503;72.32\r\n"02 - Frosen oppalen laks";"2026U29 - 2026U29";838;72.37\r\n"02 - Frosen oppalen laks";"2026U30 - 2026U30";736;72.08\r\n"02 - Frosen oppalen laks";"2026U31 - 2026U31";697;72.79\r\n"02 - Frosen oppalen laks";"2026U32 - 2026U32";638;74.09\r\n"02 - Frosen oppalen laks";"2026U33 - 2026U33";751;69.12\r\n"02 - Frosen oppalen laks";"2026U34 - 2026U34";727;75.03\r\n"02 - Frosen oppalen laks";"2026U35 - 2026U35";720;72.94\r\n"02 - Frosen oppalen laks";"2026U36 - 2026U36";546;68.07\r\n'

In [43]:
import io
df1 = pd.read_csv(io.StringIO(r_csv), delimiter = ';')

In [44]:
df1.tail(8)

,VareGrupper2 - varegruppe,Tid - uke,Vekt - Vekt (tonn),Kilopris - Kilopris (kr)
168,02 - Frosen oppalen laks,2026U29 - 2026U29,838,72.37
169,02 - Frosen oppalen laks,2026U30 - 2026U30,736,72.08
170,02 - Frosen oppalen laks,2026U31 - 2026U31,697,72.79
171,02 - Frosen oppalen laks,2026U32 - 2026U32,638,74.09
172,02 - Frosen oppalen laks,2026U33 - 2026U33,751,69.12
173,02 - Frosen oppalen laks,2026U34 - 2026U34,727,75.03
174,02 - Frosen oppalen laks,2026U35 - 2026U35,720,72.94
175,02 - Frosen oppalen laks,2026U36 - 2026U36,546,68.07